---
title: "tidy_data_class3"
output: html_document
date: "2026-09-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(tidyverse)
library(readxl)
library(haven)
```
# loading datasets
```{r}
pulse_df =
  haven::read_sas("data_file/public_pulse_data.sas7bdat") |> 
  janitor::clean_names()
```


# tidying data

```{r}
pulse_tidy_df = 
  pulse_df |> 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", # where should you send the column names
    names_prefix = "bdi_score_",
    values_to = "bdi_score" # where should you send the values, to a column
  ) |> 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )

```

# practicing with litters data

```{r}
pulse_df =
  read_csv("data_file/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(litter_number, gd0_weight, gd18_weight) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
  ) |> 
  mutate(
    gd_number = recode_values(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18,
    )
  )
```








